version: "3"

services:
  firefox:
    image: selenium/standalone-firefox
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - mynetwork

  rustlibs:
    image: rust:buster
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge